const deck = [
	{
		value: 2,
		altValue: 2,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/2_of_hearts.png",
		inPlay: null,
	},
	{
		value: 2,
		altValue: 2,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/2_of_spades.png",
		inPlay: null,
	},
	{
		value: 2,
		altValue: 2,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/2_of_diamonds.png",
		inPlay: null,
	},
	{
		value: 2,
		altValue: 2,
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/2_of_clubs.png",
		inPlay: null,
	},
	{
		value: 3,
		altValue: 3,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/3_of_hearts.png",
		inPlay: null,
	},
	{
		value: 3,
		altValue: 3,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/3_of_spades.png",
		inPlay: null,
	},
	{
		value: 3,
		altValue: 3,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/3_of_diamonds.png",
		inPlay: null,
	},
	{
		value: 3,
		altValue: 3,
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/3_of_clubs.png",
		inPlay: null,
	},
	{
		value: 4,
		altValue: 4,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/4_of_hearts.png",
		inPlay: null,
	},
	{
		value: 4,
		altValue: 4,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/4_of_spades.png",
		inPlay: null,
	},
	{
		value: 4,
		altValue: 4,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/4_of_diamonds.png",
		inPlay: null,
	},
	{
		value: 4,
		altValue: 4,
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/4_of_clubs.png",
		inPlay: null,
	},
	{
		value: 5,
		altValue: 5,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/5_of_hearts.png",
		inPlay: null,
	},
	{
		value: 5,
		altValue: 5,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/5_of_spades.png",
		inPlay: null,
	},
	{
		value: 5,
		altValue: 5,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/5_of_diamonds.png",
		inPlay: null,
	},
	{
		value: 5,
		altValue: 5,
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/5_of_clubs.png",
		inPlay: null,
	},
	{
		value: 6,
		altValue: 6,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/6_of_hearts.png",
		inPlay: null,
	},
	{
		value: 6,
		altValue: 6,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/6_of_spades.png",
		inPlay: null,
	},
	{
		value: 6,
		altValue: 6,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/6_of_diamonds.png",
		inPlay: null,
	},
	{
		value: 6,
		altValue: 6,
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/6_of_clubs.png",
		inPlay: null,
	},
	{
		value: 7,
		altValue: 7,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/7_of_hearts.png",
		inPlay: null,
	},
	{
		value: 7,
		altValue: 7,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/7_of_spades.png",
		inPlay: null,
	},
	{
		value: 7,
		altValue: 7,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/7_of_diamonds.png",
		inPlay: null,
	},
	{
		value: 7,
		altValue: 7,
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/7_of_clubs.png",
		inPlay: null,
	},
	{
		value: 8,
		altValue: 8,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/8_of_hearts.png",
		inPlay: null,
	},
	{
		value: 8,
		altValue: 8,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/8_of_spades.png",
		inPlay: null,
	},
	{
		value: 8,
		altValue: 8,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/8_of_diamonds.png",
		inPlay: null,
	},
	{
		value: 8,
		altValue: 8,
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/8_of_clubs.png",
		inPlay: null,
	},
	{
		value: 9,
		altValue: 9,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/9_of_hearts.png",
		inPlay: null,
	},
	{
		value: 9,
		altValue: 9,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/9_of_spades.png",
		inPlay: null,
	},
	{
		value: 9,
		altValue: 9,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/9_of_diamonds.png",
		inPlay: null,
	},
	{
		value: 9,
		altValue: 9,
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/9_of_clubs.png",
		inPlay: null,
	},
	{
		value: 10,
		altValue: 10,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/10_of_hearts.png",
		inPlay: null,
	},
	{
		value: 10,
		altValue: 10,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/10_of_spades.png",
		inPlay: null,
	},
	{
		value: 10,
		altValue: 10,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/10_of_diamonds.png",
		inPlay: null,
	},
	{
		value: 10,
		altValue: 10,
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/10_of_clubs.png",
		inPlay: null,
	},
	{
		value: 11,
		altValue: 11,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/jack_of_hearts2.png",
		inPlay: null,
	},
	{
		value: 11,
		altValue: 11,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/jack_of_spades2.png",
		inPlay: null,
	},
	{
		value: 11,
		altValue: 11,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/jack_of_diamonds2.png",
		inPlay: null,
	},
	{
		value: 11,
		altValue: 11,
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/jack_of_clubs2.png",
		inPlay: null,
	},
	{
		value: 12,
		altValue: 12,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/queen_of_hearts2.png",
		inPlay: null,
	},
	{
		value: 12,
		altValue: 12,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/queen_of_spades2.png",
		inPlay: null,
	},
	{
		value: 12,
		altValue: 12,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/queen_of_diamonds2.png",
		inPlay: null,
	},
	{
		value: 12,
		altValue: 12,
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/queen_of_clubs2.png",
		inPlay: null,
	},
	{
		value: 13,
		altValue: 13,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/king_of_hearts2.png",
		inPlay: null,
	},
	{
		value: 13,
		altValue: 13,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/king_of_spades2.png",
		inPlay: null,
	},
	{
		value: 13,
		altValue: 13,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/king_of_diamonds2.png",
		inPlay: null,
	},
	{
		value: 13,
		altValue: 13
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/king_of_clubs2.png",
		inPlay: null,
	},
	{
		value: 14,
		altValue: 1,
		suit: "hearts",
		image: "images/Playing_cards/playing-cards/ace_of_hearts.png",
		inPlay: null,
	},
	{
		value: 14,
		altValue: 1,
		suit: "spades",
		image: "images/Playing_cards/playing-cards/ace_of_spades.png",
		inPlay: null,
	},
	{
		value: 14,
		altValue: 1,
		suit: "diamonds",
		image: "images/Playing_cards/playing-cards/ace_of_diamonds.png",
		inPlay: null,
	},
	{
		value: 14,
		altValue: 1,
		suit: "clubs",
		image: "images/Playing_cards/playing-cards/ace_of_clubs.png",
		inPlay: null,
	}
]